### PR TITLE
Add MUS-X plugin

### PR DESCRIPTION
**Pull request by Jojosito**

### CODE REVIEW

**Comment by falkTX** [comment]
Thanks for the PR! Always nice to see plugin devs contributing directly!

We were just about to release 24.09, we can merge this after the release is done

One thing though, you have some presets in your repo, we should see about including them in Cardinal too.
There is a section about presets in plugins/Makefile

**Comment by falkTX** [comment]
> Hello Filipe, I just saw you already released 24.09 In my build, the factory presets are already included, probably via "RESOURCE_FILES += $(wildcard */presets)". Is there anything else to do?

There is a step to add these resources to Cardinal, but I can do that after merging.
Thanks!

**Comment by falkTX** [comment]
Resources added in 2798ef3819fa3265cc850c150536491dd33ff43b

**Comment by Jojosito** [comment]
Thanks for merging!
However, I noticed that in the Windows VST plugin, the Delay module is buggy. It works well in Windows Rack, as well as in Linux Cardinal.
I'll have to do some more testing and troubleshooting...

**Pull request merged**
