### PR TITLE
Add EnigmaCurry

### PR DESCRIPTION
**Pull request by EnigmaCurry**
I am starting to test my plugins in Cardinal. This is not ready to merge yet, but if you see some stuff that needs to change, please let me know.

### CODE REVIEW

**Comment by falkTX** [comment]
the setup so far looks ok. but the readme and license information is missing

**Comment by EnigmaCurry** [comment]
> the setup so far looks ok. but the readme and license information is missing

I'm not sure what you mean, my plugin repo has a readme and a license, and both linked in plugin.json. Do you mean adding to docs/LICENSES.md? Where else?

**Comment by falkTX** [comment]
the last one is not needed, please revert it. likely you have some build files still around that generate the conflict. there is always only a need to set the custom for 1 side, not both.

the license stuff needs to be filled regarding artwork, on the same file you modified but further down.
we need to specify all the licensing for the files included in the repo, as a way to alleviate the burden for distribution packages.

then it is just also updating the cardinal main readme to mention your modules being part of it.

**Comment by falkTX** [comment]
this seems good to me know, anything else still missing or is this okay for merging?

**Comment by EnigmaCurry** [comment]
Yea, looks like everything works now, thank you very much!

**Comment by falkTX** [comment]
ok lets merge! thanks

**Pull request merged**
