### PR TITLE
CV funk v2.0.9

### PR DESCRIPTION
**Pull request by codygeary**
CV funk v2.0.9

Adds 4 new modules:
Step Wave - 8-stage variable waveform sequencer
Arrange - A 7-channel sequencer with variable sequence length.
Preeeeeeeeeeessed Duck - 16 channel version of Pressed Duck
Tri Delay - A 3-tap stereo delay

Many bugfixes and small updates:
Ouros now supports full poly, with extensive simd optimizations to make the CPU more efficient.
Morta now supports full poly.
Envelope Array, Penta, Hex, now have poly CV out options in the context menu
Strings supports poly outputs when the first input is patched alone.
Pressed Duck and brother support poly inputs.
Many many other new features, see manual. I tried to implement every requested feature I could manage.

Signals - fixed outputs from poly inputs.
Strings - fixed wrong augmented chords
Arrange - added option for up to 2048 sequencer steps. Added option to ouput poly from the top channel. Fixed a bug where the sequencer could get stuck at certain steps that were even divisions, solved by replacing floor with round. Reduced CPU waste.
Step Wave - added quantizer option. When sequencer is off, stage changes by button press send a trigger to the gate output. This option makes it easier to program the module and have your downstream patch respond to stage changes. Edit to make the clock wait for the json saved clock cycle before processing a new clock input, preventing hyper clocking at startup.
Pressed Duck - fixed a bug caused by unpatching and repatching inputs. Fixed bug in the mutes where muted inputs would still raise the headroom.
Ouros and HexMod - increased the frequency range of knobs and inputs.
Envelope Array - added polyphonic input handling

### CODE REVIEW

**Comment by falkTX** [comment]
Thanks for the update!

CI for macOS is broken at the moment, as I try to add a debug build for testing.
I want to wait fixing this before merging any PRs.

**Comment by codygeary** [comment]
Hold off on updating this one, once you get it fixed.  I'm working on a bugfix for v2.0.9 and will have to re-link the repo again.

**Comment by dromer** [comment]
@codygeary please merge the main branch so we can re-run the CI :)

**Comment by codygeary** [comment]
Thanks!  I will soon. I'm very close to making a 2.0.11 release, so it might as well wait for that.

**Comment by rl2939** [comment]
Since you made the 2.0.11 release, could you please send the updates to Cardinal and merge the current branch as well?

**Comment by codygeary** [comment]
V2.0.10 includes bugfixes:

Pressed Duck and big Duck - Fixed clickless mutes. Fixed channel normalization issues introduced in last update. Added optional supersampling.
Arrange - Improved detection of gate inputs.
Tri Delay - Fixed issue with Tap 1 and Tap 2 not responding to pan and feedback positioning. Adjusted feedback levels.

Version 2.0.11 Updates

Added 'smart knobs' to Arrange and Morta. Interacting with the knob overrides the automation.
Shift-click on a knob while in record mode on Arrange to map to all sequencer stages.
Fixed Max-stages bug in Arrange, where recording past step 128 would not work right.
Moved knob code to within the widget to prevent crosstalk between functions.
Added 'solo' mutes to Pressed Duck and the bigger Duck. Shift-click mute buttons to solo them.
Fixed a bug in PentaSequencer where some knobMappings would not update properly.
Fixed rounding in Strings.
Added clipping mask to Tri Delay screen.
Ouros display update, makes it smoother.
Signals - fixed poly cable handling bug.
Syncro, Strings and StepWave, changed round to roundf to avoid overloaded function errors on some platforms.

**Comment by dromer** [comment]
@codygeary you'll want to sync with the current develop branch so that the CI will succeed :)

**Comment by codygeary** [comment]
> @codygeary you'll want to sync with the current develop branch so that the CI will succeed :)

I think I did? I synced and fetched origin before I ran 'git submodule update --remote' and pushed my submodule. Hope it works!

**Comment by dromer** [comment]
What I usually do is:

```bash
git checkout develop
git pull
git checkout <my_branch>
git merge develop
```

**Comment by dromer** [comment]
Actually I'm not sure why the headless build fails :shrug:

**Comment by falkTX** [comment]
Thanks for the update! just in time for release tomorrow

**Pull request merged**
