### PR TITLE
Add SynthKit.

### PR DESCRIPTION
**Pull request by rl2939**
Adds the modules from SynthKit.

### CODE REVIEW

**Comment by dromer** [comment]
@rl2939 while we appreciate you adding modules to Cardinal we also need some good motivation to add more modules.

We are slowly reaching the limits of what we can feasibly add to the program. Partially because of what our automated builds can handle, but we also want to curate quality over quantity.

Please add some good motivation on why we should add certain modules and how they would enhance the project.

At the moment we want to focus on module updates (there are still plenty that need some attention) and bugfixes.

thnx!

**Comment by dromer** [comment]
For instance SynthKit provides basic logic modules that we already have from other modules in Cardinal.

So while they look nice and they can be added, what makes them stand out that warrants inclusion?

**Comment by rl2939** [comment]
> Please add some good motivation on why we should add certain modules and how they would enhance the project.

Thats fair. The reason I added this set of modules was because I wanted the two sequencers in the collection. Both sequencers have built in pitch quantization, and don't skip the first step on reset.

> For instance SynthKit provides basic logic modules that we already have from other modules in Cardinal.

I'll see if I can pair the collection down so that the automated system builds just those two sequencers.

**Comment by dromer** [comment]
I didn't mean to selectively take modules from the specific plugin, but we really have to consider what we will add to Cardinal as a whole. We want to be able to maintain the project for a long time and having a reasonable size for both the CI and the User has to be considered with that :)

**Comment by falkTX** [comment]
I am closing this as "won't fix" as these modules are from the same developer as DrumKit and they have requested to not have their modules in Cardinal. See #772

**Pull request closed without merging**
