### PR TITLE
Order modules according to cable connections

### PR DESCRIPTION
**Pull request by vitreo12**
Hello!

This PR allows the `internal->modules` to be ordered according to their cable connections, and not to the order in which they were created.

WIth this, there is now a guarantee that no single sample feedback is introduced between cable connections, unless feedback connections are in place.

As an example, this is a simple patch that plays a sine wave through a sequence of 54 modules to measure the difference of the starting signal with the end one. As you can see, with the current implementation there is definitely a delay introduced by the connections, since the audio process steps through the `modules` in regards of the order in which they were created, ignoring which modules should come first according to the cable connections:

Screenshot_20221101_003217

On the other hand, with this PR, the signal flow is actually showing a null sum between the starting signal and the end one, as we would expect following the cables:

Screenshot_20221101_004514

As a side result, this PR guarantees that all feedback connections are always only introducing a one sample delay, and not more.

### CODE REVIEW

**Comment by falkTX** [comment]
oh wow, quite impressive!
thanks a lot of this, have been on my mind for a while in order to finalize the minimal-latency case, but typically have things with more priority to do.

when testing, do you see any performance differences due to recalculation on cable connection changes?

looking at the changes, I think we should make the reordering optional, so that loading a patch makes all the connections and only reorders them at the very end. we can add a new bool var to the engine internal data struct, which is false by default unless when loading a patch.

**Comment by vitreo12** [comment]
According to my tests, there are no performance differences since the re-ordering happens only on a new cable connection (`Engine_updateConnected`), and not within the actual DSP loop.

**Comment by falkTX** [comment]
> According to my tests, there are no performance differences since the re-ordering happens only on a new cable connection (`Engine_updateConnected`), and not within the actual DSP loop.

that is good, but I meant in the "gui gets stuck for a few ms because there are a lot of cables to go through one by one" case.
need to test this myself with a over-the-top patch, to see if new connections cause GUI hickups. I suspect not, but just want to double-check since I also run Cardinal on low-power systems too.

**Comment by vitreo12** [comment]
Ah, I see! I could only test it on my machine which is quite high-specced. I didn't notice anything there with patches with 50+ modules.

Let me know how your findings go :)

**Comment by falkTX** [comment]
there is only so much time in a day, I am merging this as-is, then only doing some small code styling adjustments.
thanks again!

**Pull request merged**
