### PR TITLE
Add Sculpt-O-Sound Vocode-O-Matic module

### PR DESCRIPTION
**Pull request by farlukar**
Builds OK.
[plugin.json](https://github.com/josbouten/Sculpt-O-Sound/blob/master/plugin.json) explicitly has GPL-3.0-or-later for the software; graphics license is mentioned as CC0 in [LICENSE.txt](https://github.com/josbouten/Sculpt-O-Sound/blob/master/LICENSE.txt), but the newer [README.md](https://github.com/josbouten/Sculpt-O-Sound/blob/master/README.md) says CC BY-NC-ND 4.0. Can it considered to be the latter or should I ask the author to clarify?

### CODE REVIEW

**Comment by farlukar** [comment]
Ugh, I managed not to get the repo included.

**Comment by dromer** [comment]
Always better to ask for clarification.

The Non-Derivative would need an explicit permission if we want to create a dark mode render as well.

**Comment by farlukar** [comment]
Looks like GitHub outages?

**Comment by farlukar** [comment]
(I know sod all about git, sorry)

**Comment by falkTX** [comment]
I cleaned up the PR and created #635 based on it, but it is a "wont-fix" as the modules require 44.1 kHz to work properly which is a blocker.

**Pull request closed without merging**
