### PR TITLE
Use simde as fallback simd implementation

### PR DESCRIPTION
**Pull request by xctan**
This patch fixes simd related issues on riscv64 platform.

### CODE REVIEW

**Comment by falkTX** [comment]
Where does simde come from? Does it need to be installed system-wide first? If so, it needs to be mentioned somewhere

**Comment by xctan** [comment]
The library comes from a system-wide package. Our patched version of
PKGBUILD includes simde as make dependency, so it will be installed before
building the package. Because simde is header-only, I wonder if it can be
integrated into include folder, just like sse2neon.

Filipe Coelho ***@***.***> 于 2022年9月9日周五 23:53写道：

**Comment by falkTX** [comment]
looking around, seems possible to enable riscv64 builds by using debian's multiarch setup similarly to how I did the ARM builds.
already tried with another DPF based plugin and it builds, though I have no hardware to test this with.

@xctan what hw do you have that is able to run cardinal? so you by any chance knows someone who would be willing to sponsor a riscv board for me? (so riscv builds can become officially supported)

**Comment by falkTX** [comment]
Merged as part of https://github.com/DISTRHO/Cardinal/commit/a5d28c2707bde032f056d90741fdcfcb9d96a578 thanks!
linux-riscv64 now enabled in CI

**Comment by xctan** [comment]
I'm working with remote headless boards and haven't tried to run cardinal either. You could contact [Wei Wu](https://github.com/lazyparser) for help in obtaining a riscv board.

**Comment by XieJiSS** [comment]
Hi @falkTX, have you got access to some RISC-V hardware? If not, I'm willing to provide SSH access to RISC-V hw boards for developing, testing & building purpose

Best Regards

**Pull request closed without merging**
