### PR TITLE
Add Computerscare modules

### PR DESCRIPTION
**Pull request by washikano**
It compiles and works in Linux. This is a result of roughly following guides, receiving advice, and trial and error. Thank you all. Dark panels pending, though.

Please let me know if I did something wrong, I'm new to this.

### CODE REVIEW

**Comment by dromer** [comment]
Hmm, you didn't add the Computerscare project as a submodule, instead you copied over the entire source tree.

This is not the way to add Rack modules!

I'm not sure if it was necessary to extern all of the modules either.

**Comment by washikano** [comment]
It was an accident as I used git submodule add etc. to add the submodule but didn't check what files were necessary. I'll sort this out when I get back home, sorry!

**Comment by washikano** [comment]
I didn't know you have to cd into plugins/<submodule> and git add files manually, commit, then go back to the project root and commit and push there. The first time I tried to add plugins/<submodule> it didn't stage the modified files so I force-staged the entire directory, hence the mess. My apologies, I hope I did everything correctly now.

**Comment by dromer** [comment]
> I didn't know you have to cd into plugins/submodule and git add files manually

That shouldn't be necessary. You do have to add the submodule folder to your main commit, but not any of its contents.

I'll check out this branch today. We should probably squash the commits so we don't get the full add+remove in the history :)

**Comment by dromer** [comment]
Ok, they all seemed to build just fine:



Now we just need to come up with the best way to create the dark panels.

**Comment by washikano** [comment]
Did I do it right? Hopefully all that remains to do is the dark panels, I'll look into it later today

**Comment by falkTX** [comment]
yes, that is perfect.

lets see if the automated CI tests now pass without issues.

**Comment by washikano** [comment]
Sorry, I don't know what's wrong this time. WASM fails to build locally too.
image

**Comment by falkTX** [comment]
wasm fails on:
```
wasm-ld: error: duplicate symbol: main
```

likely one of the files included on the makefile is a test one meant for unit-testing or other stuff not usable in a plugin version. whatever one contains the "main" entry point call
we need to remove that file from the build using the `filter-out` method on top of the wildcard, as done for. a few others.

the debug zip file failing might be due to finally getting out of disk space on GH size..
either that or there is a recursive symlink that makes the zipping explode in size

**Comment by washikano** [comment]
mark dode test
image
image

**Comment by washikano** [comment]
There is a special case with the ComputerscareBlank module; it can be resized, but the color of the background is defined in ComputerscareBlank.cpp, so basically the ComputerscareBlankPanel.svg is drawn on top of a resizable box with colors independent from the .svg, thus it can't be modified with dep.cpp

An attempt was made to prepare the module for dark mode; if you add the module to a patch or load a patch containing the module, the box drawn behind the .svg will have the correct colors for that mode. However, if you change to another mode (light to dark, or vice-versa), the colors of the box won't change unless you add another instance of ComputerscareBlank, or the patch is reloaded.

Here's a video:

https://github.com/DISTRHO/Cardinal/assets/156562233/09b06e97-147c-4e79-ace4-178288537f1f

**Comment by dromer** [comment]
Hmm, this custom `digital-7.ttf` font license is somewhat problematic.

Maybe we can convince Computerscare to use the `Segment7Standard.ttf` font which is used by many other modules for their 7 segment displays.

**Comment by washikano** [comment]
If we get no response, would it be ok to just quietly change the font? The rest of the code can follow upstream...

Also, some text labels are drawn by Computerscare.hpp for the rest of the modules, but I can't find a way to properly invert their colors for dark mode (similar issue to a previous issue with ComputerscareBlank, where the panel's background wouldn't change for dark or light mode unless the patch was reloaded). The only solution I can think of that doesn't involve re-writing whole blocks of code and potentially breaking the rest of the modules is to just draw shapes of contrasting colors under the labels... the panels will look SUPER UGLY but in this case that's more of a plus.

Another, more nuclear option I've been thinking of is to fork Computerscare, change the artwork, and call it PCBoo... the compromise would be potentially losing compatibility with VCV Rack

**Comment by falkTX** [comment]
typically what we do is a soft fork, by forking but submitting our changes upstream with anything that breaks original VCV Rack usage under a cardinal specific macro.

that way we can keep the light/dark mode things on the module code for cardinal, while the original behaviour remains for VCV Rack.

PS: we have merged CVfunk recently, so now there are conflicts regarding your PR. but since this involves a soft fork I think I can take it from here.

**Comment by falkTX** [comment]
fork is created in https://github.com/CardinalModules/computerscare-vcv-modules

we can have the cardinal specific code under `USING_CARDINAL_NOT_RACK` C++ macro, with `settings::preferDarkPanels` as the way to dynamically check if using light or dark mode.

**Comment by washikano** [comment]
a janky fix for a janky set of modules, I'll see if I can get in touch with Adam about changing the font upstream but in the meantime I've already done that with this branch, if there's no problem

**Comment by falkTX** [comment]
Sorry for taking long on this, life gets in the way of fun stuff sometimes.
Merging now, will do a small tweak just to get the folystickfigure panel looking brighter in white theme mode, everything else is fine! Thanks!

**Comment by falkTX** [comment]
btw I pushed your changes to https://github.com/CardinalModules/computerscare-vcv-modules
we should use that org for module forks, if you still have more to do just ping me and I add you to the team

**Comment by kawa-sanmyaku** [comment]
@falkTX good evening, I'd like to open a pull request that the CardinalModules repo; it includes module updates and a new module, they're very minor so no rush ^^

**Comment by kawa-sanmyaku** [comment]
in fact it's not necessary that I make it since it'd just be merging changes directly from upstream, not my own repo

**Comment by dromer** [comment]
@kawa-sanmyaku I've already updated the master branch to be synchronized with upstream.

**Pull request merged**
