### PR TITLE
Phase Output

### PR DESCRIPTION
**Pull request by zezic**
Added the beat phase output to the HostTime module.

### CODE REVIEW

**Comment by zezic** [comment]
Preview:

**Comment by falkTX** [comment]
Oh nice! Do we need to mention that this is phase per beat? I wonder if phase per clock or phase per bar would be useful too

**Comment by zezic** [comment]
I doubt if phase per clock would be useful for anyone, but phase per bar might be useful in some cases. I can add it and make the labels more obvious.

**Comment by falkTX** [comment]
Fair enough. Let me know if we need to make the panel bigger, in case the labels dont fit

**Comment by zezic** [comment]
No no, panel is already big enough. Usually the modules with such number of elements can fit in 3HP easily. Example:

**Comment by falkTX** [comment]
Got it. And yeah I guess it makes sense to reduce the size, not increase it, if it matches what other modules do.
It becomes hard to recognize though.

**Comment by zezic** [comment]
Done. Added the bar phase output. I hope it's monotonic...

**Comment by falkTX** [comment]
Real nice, thank you

**Pull request merged**
