### PR TITLE
CVfunk add Magnets

### PR DESCRIPTION
**Pull request by codygeary**
Starting a new PR, I reupdated my branch.  I made a new module called Magnets, so here it is added. Cheers!

### CODE REVIEW

**Comment by dromer** [comment]
This all builds and runs fine.
Only minor issue I see with Strings is that the labels next to each row are quite unreadable in light mode:

**Comment by codygeary** [comment]
if you switch between light and dark mode the font color should update when you either reload the patch or drop another module.

**Comment by codygeary** [comment]
Ah ha! I figured out how to make this font color changing code much more elegant, it turned out to be easy to fix afterall.  I'll update this PR later today with it

**Comment by dromer** [comment]
Looking good. I think the build failures were a glitch in GH Actions, will try to restart them once that button is available.

**Comment by codygeary** [comment]
https://patchstorage.com/cv-funk-cardinal-demo-hexmod-oscillator/

**Pull request merged**
