### PR TITLE
Add Mojo.

### PR DESCRIPTION
**Pull request by TheGuyWhoo**
It should work now, idk.

### CODE REVIEW

**Comment by dromer** [comment]
Should need some work for the bright panels (particularly Sheep).

**Comment by TheGuyWhoo** [comment]
Like this:

dogs2
pigs2
sheep2

**Comment by TheGuyWhoo** [comment]
Made some adjustments

dogs
pigs
sheep

**Comment by TheGuyWhoo** [comment]
Gonna close this one as well, made a capitalization mistake.

**Pull request closed without merging**
