### PR TITLE
Add HetrickCV

### PR DESCRIPTION
**Pull request by dromer**
Anything I missed?

### CODE REVIEW

**Comment by falkTX** [comment]
Your editor broke the end-of-line whitespace in ` doc/LICENSES.md` (see diff)
Please fix this, the space at the end is intentional, it is how we generate newlines in markdown.

**Comment by falkTX** [comment]
Also, you forgot to add the plugin/res symlink here

**Comment by dromer** [comment]
done and done :)

**Comment by falkTX** [comment]
Nice, thanks!

**Comment by dromer** [comment]
The inversion of the panels works but it changes the logo (which is embedded).

Not sure what the best approach is to keep the logo as intact as possible (primarily not invert the orange `Cv`)

**Pull request merged**
