### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by jn64**
Just a simple template to ensure version, plugin type, OS, and DAW/host are mentioned in bug reports.

## Previews

[New issue menu](https://github.com/jn64/Cardinal/issues/new/choose)

[Bug report form](https://github.com/jn64/Cardinal/issues/new?template=bug.yaml)

The dropdown for plugin type allows multiple selections.

[Example bug report](https://github.com/jn64/Cardinal/issues/1)

### CODE REVIEW

**Comment by dromer** [comment]
For feature requests it might be good to redirect all plugin requests to the wiki and/or discussion.

**Comment by jn64** [comment]
Done. Here's what the "New issue" page will look like: https://github.com/jn64/Cardinal/issues/new/choose

**Comment by dromer** [comment]
@falkTX any suggestions for this? I think it would be good to merge and have as a baseline for future tickets

**Comment by jn64** [comment]
I could add a optional field field for DAW/host. Any other commonly requested/missing info in issues?

**Comment by dromer** [comment]
Sounds good! also probably change the suggested Cardinal release to the latest: 23.10

**Comment by falkTX** [comment]
Merging this now, thanks a lot!

Want to do some tweaking, but this is a great start.

**Pull request merged**
